"""Domain contracts for the AI Migration Control Tower."""

from migration_factory.control_tower.domain.checksums import (
    canonical_json,
    canonical_json_bytes,
    canonical_json_text,
    sha256_canonical_json,
    sha256_checksum,
    sha256_hex,
    stream_sha256,
    utc_now,
    utc_now_text,
)
from migration_factory.control_tower.domain.artifacts import ArtifactHashResult
from migration_factory.control_tower.domain.entities import (
    ArtifactRecord,
    AuditRecord,
    MigrationJobRecord,
    PipelineDefinitionRecord,
    RunConfigurationRecord,
    RunEventRecord,
    RunnerProfileRecord,
    StageRunRecord,
)
from migration_factory.control_tower.domain.errors import (
    ArtifactHashError,
    ArtifactPathError,
    CompatibilityError,
    ConcurrencyConflictError,
    ControlTowerDomainError,
    ControlTowerError,
    InvalidJobStateTransitionError,
    NotFoundError,
    RegistrationConflictError,
    StaleVersionError,
    StorageIntegrityError,
)
from migration_factory.control_tower.domain.states import (
    JobState,
    StageState,
    TargetProofLevel,
)
from migration_factory.control_tower.domain.transitions import (
    JOB_STATE_TRANSITIONS,
    TERMINAL_JOB_STATES,
    allowed_job_transitions_from,
    can_transition_job_state,
    is_terminal_job_state,
    validate_job_state_transition,
)

__all__ = [
    "ArtifactHashResult",
    "ArtifactRecord",
    "ArtifactHashError",
    "ArtifactPathError",
    "AuditRecord",
    "CompatibilityError",
    "ConcurrencyConflictError",
    "ControlTowerDomainError",
    "ControlTowerError",
    "InvalidJobStateTransitionError",
    "JOB_STATE_TRANSITIONS",
    "JobState",
    "MigrationJobRecord",
    "NotFoundError",
    "PipelineDefinitionRecord",
    "RegistrationConflictError",
    "RunConfigurationRecord",
    "RunEventRecord",
    "RunnerProfileRecord",
    "StageRunRecord",
    "StageState",
    "StaleVersionError",
    "StorageIntegrityError",
    "TERMINAL_JOB_STATES",
    "TargetProofLevel",
    "allowed_job_transitions_from",
    "can_transition_job_state",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_json_text",
    "is_terminal_job_state",
    "sha256_canonical_json",
    "sha256_checksum",
    "sha256_hex",
    "stream_sha256",
    "utc_now",
    "utc_now_text",
    "validate_job_state_transition",
]
