from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class CapabilityInventoryResult:
    report_path: Path
    summary_path: Path
    payload: dict[str, Any]


CAPABILITY_ENTRIES: tuple[dict[str, Any], ...] = (
    {
        "capability_id": "JAVA_VERSION_ALIGNMENT",
        "category": "route_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["java-17"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["migration_plan.yaml", "ledger.json"],
        "notes": "Factory aligns Java target across planned migration hops and Java-specific validation units.",
    },
    {
        "capability_id": "SPRING_BOOT_VERSION_ALIGNMENT",
        "category": "route_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-2-7-stabilization", "spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["migration_plan.yaml", "ledger.json"],
        "notes": "Factory performs staged Spring Boot target alignment across intermediate and final hops.",
    },
    {
        "capability_id": "SPRING_BOOT_MULTI_HOP_ROUTE",
        "category": "planning",
        "capability_type": "DETECT",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "planning",
        "evidence_artifacts": ["migration_plan.yaml", "approval_request.json"],
        "notes": "Planner can select governed multi-hop Boot migration routes when direct jump is high risk.",
    },
    {
        "capability_id": "JDK_AWARE_ANALYSIS_PREVIEW",
        "category": "analysis",
        "capability_type": "DETECT",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "analysis",
        "evidence_artifacts": ["analysis_facts.json", "migration_plan.yaml"],
        "notes": "Analysis and planning preserve JDK-aware route metadata before transformation begins.",
    },
    {
        "capability_id": "JDK_AWARE_TRANSFORMATION_UNITS",
        "category": "analysis",
        "capability_type": "DETECT",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["java-17", "jaxb-jakarta", "spring-boot-3-5-14"],
        "lifecycle_phase": "planning",
        "evidence_artifacts": ["migration_plan.yaml", "ledger.json"],
        "notes": "Transformation plan carries per-unit JDK/hop metadata so sandbox execution follows correct runtime.",
    },
    {
        "capability_id": "IMPORT_JAVAX_VALIDATION_TO_JAKARTA",
        "category": "namespace_migration",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Framework migration path covers validation namespace import modernization to Jakarta.",
    },
    {
        "capability_id": "IMPORT_JAVAX_XML_BIND_TO_JAKARTA",
        "category": "namespace_migration",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["jaxb-jakarta", "spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Factory covers JAXB namespace migration through dedicated Jakarta XML Bind unit and Boot 3 modernization flow.",
    },
    {
        "capability_id": "IMPORT_JAVAX_SERVLET_TO_JAKARTA",
        "category": "namespace_migration",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Framework migration path covers servlet namespace import modernization to Jakarta.",
    },
    {
        "capability_id": "JAKARTA_XML_BIND_DEPENDENCY_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["jaxb-jakarta"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Dedicated JAXB Jakarta unit aligns javax.xml.bind dependencies to jakarta.xml.bind-api without touching legacy repo.",
    },
    {
        "capability_id": "LOMBOK_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["java-17"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic Lombok version alignment before Java 17 validation.",
    },
    {
        "capability_id": "JACOCO_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["java-17"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic JaCoCo version alignment before Java 17 validation.",
    },
    {
        "capability_id": "SLF4J_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic SLF4J/logging alignment for Boot 3 routes.",
    },
    {
        "capability_id": "JACKSON_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-2-7-stabilization", "spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Hop-aware Jackson dependency management alignment.",
    },
    {
        "capability_id": "SPRING_SECURITY_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic Spring Security dependency alignment for Boot 3.",
    },
    {
        "capability_id": "JJWT_VERSION_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic JJWT version alignment for direct, property, and dependencyManagement forms.",
    },
    {
        "capability_id": "JAKARTA_VALIDATION_DEPENDENCY_ALIGNMENT",
        "category": "maven_alignment",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Adds validation dependency support for Boot 3 when usage detected.",
    },
    {
        "capability_id": "SPRING_DATA_SORT_BY_MIGRATION",
        "category": "source_patch",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic Spring Data Sort constructor modernization.",
    },
    {
        "capability_id": "MOCKBEAN_TO_MOCKITOBEAN",
        "category": "test_modernization",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic Spring Boot test annotation modernization for Boot 3.",
    },
    {
        "capability_id": "INITMOCKS_TO_OPENMOCKS",
        "category": "test_modernization",
        "capability_type": "TRANSFORM",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Deterministic Mockito initMocks to openMocks test modernization.",
    },
    {
        "capability_id": "JUNEAU_VERSION_ALIGNMENT_OR_REVIEW",
        "category": "review_gate",
        "capability_type": "REVIEW_GATE",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["ledger.json"],
        "notes": "Review-only by default; deterministic version alignment only when profile explicitly configures Juneau target.",
    },
    {
        "capability_id": "POWERMOCK_LEGACY_TEST_STRATEGY",
        "category": "review_gate",
        "capability_type": "REVIEW_GATE",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["powermock_review.json", "ledger.json"],
        "notes": "PowerMock dependency and usage gate for legacy test modernization risk.",
    },
    {
        "capability_id": "JAKARTA_HYBRID_STRATEGY",
        "category": "review_gate",
        "capability_type": "REVIEW_GATE",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["jakarta_hybrid_strategy.json", "ledger.json"],
        "notes": "Classifies javax usage into deterministic, dependency, and human-review paths.",
    },
    {
        "capability_id": "API_CONTRACT_REVIEW_GATE",
        "category": "review_gate",
        "capability_type": "REVIEW_GATE",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "finalization",
        "evidence_artifacts": ["api_contract_review.json"],
        "notes": "Detects likely HTTP status, advice, validation, and Problem payload drift from failed tests.",
    },
    {
        "capability_id": "AZURE_SDK_MIGRATION_PLAYBOOK",
        "category": "review_gate",
        "capability_type": "REVIEW_GATE",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": True,
        "supported_units": ["spring-boot-3-5-14"],
        "lifecycle_phase": "transform",
        "evidence_artifacts": ["azure_sdk_migration_review.json", "ledger.json"],
        "notes": "Detects old/new Azure SDK coexistence and source usage hints without rewriting Azure APIs.",
    },
    {
        "capability_id": "CONSUMER_COMPATIBILITY_VALIDATION",
        "category": "validation_gate",
        "capability_type": "CONSUMER_VALIDATION",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "post_validation",
        "evidence_artifacts": ["consumer_compatibility_report.json", "consumer_compatibility_summary.md"],
        "notes": "Optional downstream consumer validation gate for migrated libraries and shared artifacts.",
    },
    {
        "capability_id": "MIGRATION_WAVE_PLANNER",
        "category": "wave_planning",
        "capability_type": "WAVE_PLANNING",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "planning",
        "evidence_artifacts": ["migration_wave_plan.json", "migration_wave_summary.md"],
        "notes": "Generic internal dependency wave planner for local Maven project sets.",
    },
    {
        "capability_id": "WAVE_TO_CONSUMER_VALIDATION_CONFIG",
        "category": "wave_planning",
        "capability_type": "WAVE_PLANNING",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "planning",
        "evidence_artifacts": ["consumer_validation_config.json", "consumer_validation_config_summary.md"],
        "notes": "Bridges migration wave plan output into consumer validation gate configuration.",
    },
    {
        "capability_id": "FAILURE_CLASSIFICATION",
        "category": "reporting",
        "capability_type": "REPORT",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "build_failure",
        "evidence_artifacts": ["post_transform_failure_classification.json"],
        "notes": "Classifies failed post-transform tests into migration-relevant categories.",
    },
    {
        "capability_id": "FAILED_SANDBOX_REPORTING",
        "category": "reporting",
        "capability_type": "REPORT",
        "safe_to_auto_apply": False,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "finalization",
        "evidence_artifacts": ["migration_report.json", "migration_summary.md"],
        "notes": "Writes final-style failure report for failed sandbox migrations with governance metadata.",
    },
    {
        "capability_id": "LLM_POLICY_GATE",
        "category": "remediation_policy",
        "capability_type": "REMEDIATION_PLAN",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "remediation",
        "evidence_artifacts": ["remediation_plan.yaml"],
        "notes": "Default-disabled LLM policy gate with explicit provider and budget guardrails.",
    },
    {
        "capability_id": "REMEDIATION_PLAN",
        "category": "remediation",
        "capability_type": "REMEDIATION_PLAN",
        "safe_to_auto_apply": False,
        "requires_human_approval": True,
        "llm_candidate": True,
        "supported_units": [],
        "lifecycle_phase": "remediation",
        "evidence_artifacts": ["remediation_plan.yaml"],
        "notes": "Plan-only remediation agent that analyzes failures and emits structured candidates.",
    },
    {
        "capability_id": "DETERMINISTIC_AUTO_REMEDIATION_LOOP",
        "category": "remediation",
        "capability_type": "AUTO_REMEDIATION",
        "safe_to_auto_apply": True,
        "requires_human_approval": False,
        "llm_candidate": False,
        "supported_units": [],
        "lifecycle_phase": "remediation",
        "evidence_artifacts": ["remediation_plan.yaml", "remediation_attempts.json", "ledger.json"],
        "notes": "Sandbox-only auto-remediation loop for safelisted deterministic candidates with rerun limits.",
    },
)


def export_factory_capability_inventory(*, output_dir: str | Path) -> CapabilityInventoryResult:
    output_root = Path(output_dir).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    capabilities = [dict(entry) for entry in CAPABILITY_ENTRIES]
    payload = {
        "capabilities": capabilities,
        "capability_ids": [entry["capability_id"] for entry in capabilities],
        "categories": sorted({str(entry["category"]) for entry in capabilities}),
        "capability_types": sorted({str(entry["capability_type"]) for entry in capabilities}),
    }
    report_path = output_root / "factory_capability_inventory.json"
    summary_path = output_root / "factory_capability_summary.md"
    report_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    summary_path.write_text(_render_summary(payload), encoding="utf-8")
    return CapabilityInventoryResult(report_path=report_path, summary_path=summary_path, payload=payload)


def _render_summary(payload: dict[str, Any]) -> str:
    lines = [
        "# Factory Capability Summary",
        "",
        f"- Capabilities: {len(list(payload.get('capabilities', []) or []))}",
        "",
    ]
    by_type: dict[str, list[dict[str, Any]]] = {}
    for capability in list(payload.get("capabilities", []) or []):
        if not isinstance(capability, dict):
            continue
        by_type.setdefault(str(capability.get("capability_type") or "UNKNOWN"), []).append(capability)
    for capability_type in sorted(by_type):
        lines.extend([f"## {capability_type}", ""])
        for item in sorted(by_type[capability_type], key=lambda entry: str(entry.get("capability_id") or "")):
            lines.append(
                f"- {item.get('capability_id', '')}: "
                f"category={item.get('category', '')}, "
                f"safe_to_auto_apply={str(item.get('safe_to_auto_apply')).lower()}, "
                f"requires_human_approval={str(item.get('requires_human_approval')).lower()}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
